-- public.actor definition

-- Drop table

-- DROP TABLE public.actor;

CREATE TABLE public.actor (
	actor_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	last_update timestamp NULL,
	CONSTRAINT actor_actor_id_not_null NOT NULL actor_id,
	CONSTRAINT actor_pkey PRIMARY KEY (actor_id)
);


-- public.address definition

-- Drop table

-- DROP TABLE public.address;

CREATE TABLE public.address (
	address_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	address text NULL,
	address2 text NULL,
	district text NULL,
	city_id int4 NULL,
	postal_code text NULL,
	phone text NULL,
	last_update timestamp NULL,
	CONSTRAINT address_address_id_not_null NOT NULL address_id,
	CONSTRAINT address_pkey PRIMARY KEY (address_id)
);


-- public.category definition

-- Drop table

-- DROP TABLE public.category;

CREATE TABLE public.category (
	category_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" text NULL,
	last_update timestamp NULL,
	CONSTRAINT category_category_id_not_null NOT NULL category_id,
	CONSTRAINT category_pkey PRIMARY KEY (category_id)
);


-- public.city definition

-- Drop table

-- DROP TABLE public.city;

CREATE TABLE public.city (
	city_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	city text NULL,
	country_id int4 NULL,
	last_update timestamp NULL,
	CONSTRAINT city_city_id_not_null NOT NULL city_id,
	CONSTRAINT city_pkey PRIMARY KEY (city_id)
);


-- public.country definition

-- Drop table

-- DROP TABLE public.country;

CREATE TABLE public.country (
	country_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	country text NULL,
	last_update timestamp NULL,
	CONSTRAINT country_country_id_not_null NOT NULL country_id,
	CONSTRAINT country_pkey PRIMARY KEY (country_id)
);


-- public.customer definition

-- Drop table

-- DROP TABLE public.customer;

CREATE TABLE public.customer (
	customer_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	store_id int4 NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	email text NULL,
	address_id int4 NULL,
	activebool text NULL,
	create_date timestamp NULL,
	last_update timestamp NULL,
	active text NULL,
	CONSTRAINT customer_customer_id_not_null NOT NULL customer_id,
	CONSTRAINT customer_pkey PRIMARY KEY (customer_id)
);


-- public.film definition

-- Drop table

-- DROP TABLE public.film;

CREATE TABLE public.film (
	film_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title text NULL,
	description text NULL,
	release_year text NULL,
	language_id int4 NULL,
	rental_duration text NULL,
	rental_rate text NULL,
	length text NULL,
	replacement_cost text NULL,
	rating text NULL,
	last_update timestamp NULL,
	special_features text NULL,
	fulltext text NULL,
	CONSTRAINT film_film_id_not_null NOT NULL film_id,
	CONSTRAINT film_pkey PRIMARY KEY (film_id)
);


-- public.film_actor definition

-- Drop table

-- DROP TABLE public.film_actor;

CREATE TABLE public.film_actor (
	actor_id int4 NULL,
	film_id int4 NULL,
	last_update timestamp NULL
);


-- public.film_category definition

-- Drop table

-- DROP TABLE public.film_category;

CREATE TABLE public.film_category (
	film_id int4 NULL,
	category_id int4 NULL,
	last_update timestamp NULL
);


-- public.inventory definition

-- Drop table

-- DROP TABLE public.inventory;

CREATE TABLE public.inventory (
	inventory_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	film_id int4 NULL,
	store_id int4 NULL,
	last_update timestamp NULL,
	CONSTRAINT inventory_inventory_id_not_null NOT NULL inventory_id,
	CONSTRAINT inventory_pkey PRIMARY KEY (inventory_id)
);


-- public."language" definition

-- Drop table

-- DROP TABLE public."language";

CREATE TABLE public."language" (
	language_id serial4 NOT NULL,
	"name" bpchar(20) NOT NULL,
	last_update timestamp DEFAULT now() NOT NULL,
	CONSTRAINT language_language_id_not_null NOT NULL language_id,
	CONSTRAINT language_last_update_not_null NOT NULL last_update,
	CONSTRAINT language_name_not_null NOT NULL name,
	CONSTRAINT language_pkey PRIMARY KEY (language_id)
);

-- Table Triggers

create trigger last_updated before
update
    on
    public.language for each row execute function last_updated();


-- public.payment definition

-- Drop table

-- DROP TABLE public.payment;

CREATE TABLE public.payment (
	payment_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	customer_id int4 NULL,
	staff_id int4 NULL,
	rental_id int4 NULL,
	amount text NULL,
	payment_date timestamp NULL,
	CONSTRAINT payment_payment_id_not_null NOT NULL payment_id,
	CONSTRAINT payment_pkey PRIMARY KEY (payment_id)
);


-- public.rental definition

-- Drop table

-- DROP TABLE public.rental;

CREATE TABLE public.rental (
	rental_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	rental_date timestamp NULL,
	inventory_id int4 NULL,
	customer_id int4 NULL,
	return_date timestamp NULL,
	staff_id int4 NULL,
	last_update timestamp NULL,
	CONSTRAINT rental_pkey PRIMARY KEY (rental_id),
	CONSTRAINT rental_rental_id_not_null NOT NULL rental_id
);


-- public.staff definition

-- Drop table

-- DROP TABLE public.staff;

CREATE TABLE public.staff (
	staff_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	address_id int4 NULL,
	email text NULL,
	store_id int4 NULL,
	active text NULL,
	username text NULL,
	"password" text NULL,
	last_update timestamp NULL,
	picture text NULL,
	CONSTRAINT staff_pkey PRIMARY KEY (staff_id),
	CONSTRAINT staff_staff_id_not_null NOT NULL staff_id
);


-- public.store definition

-- Drop table

-- DROP TABLE public.store;

CREATE TABLE public.store (
	store_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	manager_staff_id int4 NULL,
	address_id int4 NULL,
	last_update timestamp NULL,
	CONSTRAINT store_pkey PRIMARY KEY (store_id),
	CONSTRAINT store_store_id_not_null NOT NULL store_id
);