from types import SimpleNamespace

import pytest

from aitexttosqlengine.db import DatabaseManager


def test_query_returns_headers_and_rows(monkeypatch):
    class DummyCursor:
        description = [SimpleNamespace(name="one")]

        def fetchall(self):
            return [(1,)]

    class DummyConnection:
        def __init__(self, **kwargs):
            assert kwargs.get("autocommit") is True

        def execute(self, query: str):
            assert query == "SELECT 1 AS one"
            return DummyCursor()

        def close(self):
            pass

    def dummy_connect(dsn: str, **kwargs):
        return DummyConnection(**kwargs)

    monkeypatch.setattr("aitexttosqlengine.db.psycopg.connect", dummy_connect)

    db = DatabaseManager("postgresql://user:pswd@localhost:5432/faq")
    headers, rows = db.query("SELECT 1 AS one")
    db.close()

    assert headers == ["one"]
    assert rows == [(1,)]


def test_initialize_schema_uses_documents_json_tables(monkeypatch):
    executed_queries = []

    class DummyConnection:
        def __init__(self, **kwargs):
            assert kwargs.get("autocommit") is True

        def execute(self, query: str):
            executed_queries.append(query)

        def close(self):
            pass

    def dummy_connect(dsn: str, **kwargs):
        return DummyConnection(**kwargs)

    monkeypatch.setattr("aitexttosqlengine.db.psycopg.connect", dummy_connect)

    db = DatabaseManager("postgresql://user:pswd@localhost:5432/faq")
    db.initialize_schema()

    assert any("DROP TABLE IF EXISTS actor" in query for query in executed_queries)
    assert any("CREATE TABLE actor" in query for query in executed_queries)
    assert any("CREATE TABLE film" in query for query in executed_queries)


def test_seed_data_reads_sql_file(monkeypatch, tmp_path):
    sql_file = tmp_path / "seed.sql"
    sql_file.write_text("INSERT INTO actor VALUES (1);\nINSERT INTO film VALUES (2);", encoding="utf-8")

    executed_queries = []

    class DummyConnection:
        def __init__(self, **kwargs):
            assert kwargs.get("autocommit") is True

        def execute(self, query: str):
            executed_queries.append(query)

        def close(self):
            pass

    def dummy_connect(dsn: str, **kwargs):
        return DummyConnection(**kwargs)

    monkeypatch.setattr("aitexttosqlengine.db.psycopg.connect", dummy_connect)

    db = DatabaseManager("postgresql://user:pswd@localhost:5432/faq")
    db.seed_data(sql_file)

    assert executed_queries == ["INSERT INTO actor VALUES (1)", "INSERT INTO film VALUES (2)"]


def test_build_create_statement_includes_comma_separated_columns(monkeypatch):
    monkeypatch.setattr("aitexttosqlengine.db.psycopg.connect", lambda dsn, **kwargs: None)

    db = DatabaseManager("postgresql://user:pswd@localhost:5432/faq")
    statement = db._build_create_statement("actor")

    assert "first_name VARCHAR(255)" in statement
    assert "last_name VARCHAR(255)" in statement
    assert "actor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in statement
    assert ",\n    first_name" in statement


def test_build_create_statement_does_not_mark_foreign_keys_as_primary_keys(monkeypatch):
    monkeypatch.setattr("aitexttosqlengine.db.psycopg.connect", lambda dsn, **kwargs: None)

    db = DatabaseManager("postgresql://user:pswd@localhost:5432/faq")
    statement = db._build_create_statement("film")

    assert "film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in statement
    assert "language_id INT" in statement
    assert "language_id INT PRIMARY KEY" not in statement
