from __future__ import annotations

import time
from pathlib import Path
from typing import Any

import psycopg

from aitexttosqlengine.documents import DOCUMENTS

DEFAULT_SEED_SQL_PATH = Path(__file__).resolve().parents[1] / ".." / "export_202607281151.sql"


class DatabaseManager:
    def __init__(self, dsn: str):
        start = time.perf_counter()
        self.conn = psycopg.connect(dsn, autocommit=True)
        elapsed = time.perf_counter() - start
        print(f"DB connect time: {elapsed:.3f}s")

    def initialize_schema(self) -> None:
        table_names = self._table_names_from_documents()
        drop_statements = [f"DROP TABLE IF EXISTS {name} CASCADE;" for name in table_names]
        create_statements = [self._build_create_statement(name) for name in table_names]

        if drop_statements:
            self.conn.execute("\n".join(drop_statements))
        if create_statements:
            self.conn.execute("\n\n".join(create_statements))

    def _table_names_from_documents(self) -> list[str]:
        table_names: list[str] = []
        for document in DOCUMENTS:
            first_line = document.splitlines()[0]
            if first_line.startswith("Table:"):
                table_names.append(first_line.split(":", 1)[1].strip())
        return table_names

    def _build_create_statement(self, table_name: str) -> str:
        schema = self._load_schema_definition(table_name)
        if not schema:
            return ""

        column_definitions = []
        for column in schema.get("columns", []):
            name = column["name"]
            definition = column.get("sql_definition") or self._default_sql_definition(column, table_name)
            column_definitions.append(f"{name} {definition}")

        return (
            f"CREATE TABLE {table_name} (\n"
            + ",\n".join(f"    {definition}" for definition in column_definitions)
            + "\n);"
        )

    def _load_schema_definition(self, table_name: str) -> dict[str, Any] | None:
        documents_file = Path(__file__).with_name("documents.json")
        with documents_file.open("r", encoding="utf-8") as handle:
            payload: dict[str, Any] = __import__("json").load(handle)

        for table in payload.get("tables", []):
            if table.get("table") == table_name:
                return table
        return None

    def _default_sql_definition(self, column: dict[str, Any], table_name: str | None = None) -> str:
        name = column["name"]
        description = (column.get("description") or "").lower()

        if "primary key" in description:
            return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if table_name and name == f"{table_name}_id":
            return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if name.endswith("_id"):
            return "INT"
        if name.endswith("_date") or name.endswith("_update"):
            return "TIMESTAMP"
        if name.endswith("_bool"):
            return "BOOLEAN"
        if name.endswith("_price") or name.endswith("_amount"):
            return "DECIMAL(10,2)"
        if name.endswith("_name") or name.endswith("_title"):
            return "VARCHAR(255)"
        if name.endswith("_email"):
            return "VARCHAR(255)"
        return "TEXT"

    def _table_name_from_column(self, column_name: str) -> str:
        return column_name[:-3] if column_name.endswith("_id") else column_name

    def seed_data(self, sql_file: str | Path | None = None) -> None:
        path = self._resolve_seed_sql_path(sql_file)
        if path is not None and path.exists():
            self._execute_sql_file(path)
            return

        self._execute_legacy_seed_data()

    def _resolve_seed_sql_path(self, sql_file: str | Path | None) -> Path | None:
        if sql_file is not None:
            return Path(sql_file)
        return DEFAULT_SEED_SQL_PATH

    def _execute_sql_file(self, sql_file: Path) -> None:
        sql = sql_file.read_text(encoding="utf-8")
        statements = [statement.strip() for statement in sql.split(";") if statement.strip()]
        for statement in statements:
            self.conn.execute(statement)

    def _execute_legacy_seed_data(self) -> None:
        self.conn.execute("""
            INSERT INTO customers (customer_id, name, email, country) VALUES
                (1, 'Alice Johnson', 'alice@example.com', 'USA'),
                (2, 'Bob Smith', 'bob@example.com', 'Canada'),
                (3, 'Charlie Brown', 'charlie@example.com', 'UK'),
                (4, 'Diana Prince', 'diana@example.com', 'India'),
                (5, 'Ethan Hunt', 'ethan@example.com', 'Australia');

            INSERT INTO products (product_id, name, category, price) VALUES
                (101, 'Laptop', 'Electronics', 1200.00),
                (102, 'Smartphone', 'Electronics', 800.00),
                (103, 'Headphones', 'Accessories', 150.00),
                (104, 'Office Chair', 'Furniture', 250.00),
                (105, 'Coffee Maker', 'Home Appliances', 90.00);

            INSERT INTO orders (order_id, customer_id, order_date, amount) VALUES
                (1001, 1, '2025-01-10', 1200.00),
                (1002, 2, '2025-01-12', 800.00),
                (1003, 1, '2025-02-05', 150.00),
                (1004, 3, '2025-02-15', 250.00),
                (1005, 4, '2025-03-01', 1200.00),
                (1006, 5, '2025-03-10', 90.00),
                (1007, 2, '2025-03-15', 150.00),
                (1008, 4, '2025-04-01', 800.00),
                (1009, 1, '2025-04-12', 250.00),
                (1010, 3, '2025-05-05', 90.00);
        """)

    def execute(self, query: str):
        return self.conn.execute(query)

    def query(self, query: str):
        start = time.perf_counter()
        result = self.conn.execute(query)
        elapsed = time.perf_counter() - start
        print(f"DB query time: {elapsed:.3f}s")
        headers = [column.name for column in result.description] if result.description else []
        return headers, result.fetchall()

    def close(self) -> None:
        self.conn.close()
