name: Trigger auto deployment for aitexttosql

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aitexttosql-AutoDeployTrigger-310540f4-e231-4523-9ac2-e5490a6b66a7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
        - name: Login to ACR
          uses: azure/docker-login@v1
          with:
           login-server: ${{ secrets.ACR_LOGIN_SERVER }}
           username: ${{ secrets.ACR_USERNAME }}
           password: ${{ secrets.ACR_PASSWORD }}

        - name : Build Image
          run : docker push ${{ secrets.ACR_LOGIN_SERVER }}/aitexttosql:${{ github.sha }}



